//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isban.MapsMB.Business.MYAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.mya.ar.bsch", ConfigurationName="MYAService.Services")]
    public interface Services {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="getEstadoCliente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getEstadoClienteReturn")]
        Isban.MapsMB.Business.MYAService.getEstadoClienteResponse getEstadoCliente(Isban.MapsMB.Business.MYAService.getEstadoClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getEstadoCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getEstadoClienteResponse> getEstadoClienteAsync(Isban.MapsMB.Business.MYAService.getEstadoClienteRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="getStatusCliente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getStatusClienteReturn")]
        Isban.MapsMB.Business.MYAService.getStatusClienteResponse getStatusCliente(Isban.MapsMB.Business.MYAService.getStatusClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getStatusCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getStatusClienteResponse> getStatusClienteAsync(Isban.MapsMB.Business.MYAService.getStatusClienteRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="getEstadoClienteV3", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getEstadoClienteV3Return")]
        Isban.MapsMB.Business.MYAService.getEstadoClienteV3Response getEstadoClienteV3(Isban.MapsMB.Business.MYAService.getEstadoClienteV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getEstadoClienteV3", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getEstadoClienteV3Response> getEstadoClienteV3Async(Isban.MapsMB.Business.MYAService.getEstadoClienteV3Request request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="updateMensaje", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateMensajeReturn")]
        Isban.MapsMB.Business.MYAService.updateMensajeResponse updateMensaje(Isban.MapsMB.Business.MYAService.updateMensajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateMensaje", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateMensajeResponse> updateMensajeAsync(Isban.MapsMB.Business.MYAService.updateMensajeRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="updateMensajeRecarga", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateMensajeRecargaReturn")]
        Isban.MapsMB.Business.MYAService.updateMensajeRecargaResponse updateMensajeRecarga(Isban.MapsMB.Business.MYAService.updateMensajeRecargaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateMensajeRecarga", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateMensajeRecargaResponse> updateMensajeRecargaAsync(Isban.MapsMB.Business.MYAService.updateMensajeRecargaRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="updateDestinos", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateDestinosReturn")]
        Isban.MapsMB.Business.MYAService.updateDestinosResponse updateDestinos(Isban.MapsMB.Business.MYAService.updateDestinosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateDestinos", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateDestinosResponse> updateDestinosAsync(Isban.MapsMB.Business.MYAService.updateDestinosRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="registrarConDestino", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="registrarConDestinoReturn")]
        Isban.MapsMB.Business.MYAService.registrarConDestinoResponse registrarConDestino(Isban.MapsMB.Business.MYAService.registrarConDestinoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="registrarConDestino", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.registrarConDestinoResponse> registrarConDestinoAsync(Isban.MapsMB.Business.MYAService.registrarConDestinoRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="getParametros", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getParametrosReturn")]
        Isban.MapsMB.Business.MYAService.getParametrosResponse getParametros(Isban.MapsMB.Business.MYAService.getParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getParametros", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getParametrosResponse> getParametrosAsync(Isban.MapsMB.Business.MYAService.getParametrosRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="registrar", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="registrarReturn")]
        Isban.MapsMB.Business.MYAService.registrarResponse registrar(Isban.MapsMB.Business.MYAService.registrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.registrarResponse> registrarAsync(Isban.MapsMB.Business.MYAService.registrarRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="updateEstadoCliente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateEstadoClienteReturn")]
        Isban.MapsMB.Business.MYAService.updateEstadoClienteResponse updateEstadoCliente(Isban.MapsMB.Business.MYAService.updateEstadoClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateEstadoCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateEstadoClienteResponse> updateEstadoClienteAsync(Isban.MapsMB.Business.MYAService.updateEstadoClienteRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="getSuscripciones", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getSuscripcionesReturn")]
        Isban.MapsMB.Business.MYAService.getSuscripcionesResponse getSuscripciones(Isban.MapsMB.Business.MYAService.getSuscripcionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSuscripciones", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getSuscripcionesResponse> getSuscripcionesAsync(Isban.MapsMB.Business.MYAService.getSuscripcionesRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="confirmarEmail", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmarEmailReturn")]
        Isban.MapsMB.Business.MYAService.confirmarEmailResponse confirmarEmail(Isban.MapsMB.Business.MYAService.confirmarEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="confirmarEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.confirmarEmailResponse> confirmarEmailAsync(Isban.MapsMB.Business.MYAService.confirmarEmailRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.mya.ar.bsch)
        [System.ServiceModel.OperationContractAttribute(Action="updateTyCWhatsapp", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateTyCWhatsappReturn")]
        Isban.MapsMB.Business.MYAService.updateTyCWhatsappResponse updateTyCWhatsapp(Isban.MapsMB.Business.MYAService.updateTyCWhatsappRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateTyCWhatsapp", ReplyAction="*")]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateTyCWhatsappResponse> updateTyCWhatsappAsync(Isban.MapsMB.Business.MYAService.updateTyCWhatsappRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstadoCliente", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getEstadoClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public getEstadoClienteRequest() {
        }
        
        public getEstadoClienteRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstadoClienteResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getEstadoClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getEstadoClienteReturn;
        
        public getEstadoClienteResponse() {
        }
        
        public getEstadoClienteResponse(string getEstadoClienteReturn) {
            this.getEstadoClienteReturn = getEstadoClienteReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusCliente", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getStatusClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public getStatusClienteRequest() {
        }
        
        public getStatusClienteRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusClienteResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getStatusClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getStatusClienteReturn;
        
        public getStatusClienteResponse() {
        }
        
        public getStatusClienteResponse(string getStatusClienteReturn) {
            this.getStatusClienteReturn = getStatusClienteReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstadoClienteV3", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getEstadoClienteV3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public getEstadoClienteV3Request() {
        }
        
        public getEstadoClienteV3Request(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstadoClienteV3Response", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getEstadoClienteV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getEstadoClienteV3Return;
        
        public getEstadoClienteV3Response() {
        }
        
        public getEstadoClienteV3Response(string getEstadoClienteV3Return) {
            this.getEstadoClienteV3Return = getEstadoClienteV3Return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMensaje", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateMensajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public updateMensajeRequest() {
        }
        
        public updateMensajeRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMensajeResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateMensajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string updateMensajeReturn;
        
        public updateMensajeResponse() {
        }
        
        public updateMensajeResponse(string updateMensajeReturn) {
            this.updateMensajeReturn = updateMensajeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMensajeRecarga", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateMensajeRecargaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public updateMensajeRecargaRequest() {
        }
        
        public updateMensajeRecargaRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMensajeRecargaResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateMensajeRecargaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string updateMensajeRecargaReturn;
        
        public updateMensajeRecargaResponse() {
        }
        
        public updateMensajeRecargaResponse(string updateMensajeRecargaReturn) {
            this.updateMensajeRecargaReturn = updateMensajeRecargaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDestinos", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateDestinosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public updateDestinosRequest() {
        }
        
        public updateDestinosRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDestinosResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateDestinosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string updateDestinosReturn;
        
        public updateDestinosResponse() {
        }
        
        public updateDestinosResponse(string updateDestinosReturn) {
            this.updateDestinosReturn = updateDestinosReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarConDestino", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class registrarConDestinoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public registrarConDestinoRequest() {
        }
        
        public registrarConDestinoRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarConDestinoResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class registrarConDestinoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string registrarConDestinoReturn;
        
        public registrarConDestinoResponse() {
        }
        
        public registrarConDestinoResponse(string registrarConDestinoReturn) {
            this.registrarConDestinoReturn = registrarConDestinoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParametros", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public getParametrosRequest() {
        }
        
        public getParametrosRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParametrosResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getParametrosReturn;
        
        public getParametrosResponse() {
        }
        
        public getParametrosResponse(string getParametrosReturn) {
            this.getParametrosReturn = getParametrosReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrar", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class registrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public registrarRequest() {
        }
        
        public registrarRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class registrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string registrarReturn;
        
        public registrarResponse() {
        }
        
        public registrarResponse(string registrarReturn) {
            this.registrarReturn = registrarReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateEstadoCliente", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateEstadoClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public updateEstadoClienteRequest() {
        }
        
        public updateEstadoClienteRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateEstadoClienteResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateEstadoClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string updateEstadoClienteReturn;
        
        public updateEstadoClienteResponse() {
        }
        
        public updateEstadoClienteResponse(string updateEstadoClienteReturn) {
            this.updateEstadoClienteReturn = updateEstadoClienteReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSuscripciones", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getSuscripcionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public getSuscripcionesRequest() {
        }
        
        public getSuscripcionesRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSuscripcionesResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class getSuscripcionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getSuscripcionesReturn;
        
        public getSuscripcionesResponse() {
        }
        
        public getSuscripcionesResponse(string getSuscripcionesReturn) {
            this.getSuscripcionesReturn = getSuscripcionesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmarEmail", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class confirmarEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public confirmarEmailRequest() {
        }
        
        public confirmarEmailRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmarEmailResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class confirmarEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string confirmarEmailReturn;
        
        public confirmarEmailResponse() {
        }
        
        public confirmarEmailResponse(string confirmarEmailReturn) {
            this.confirmarEmailReturn = confirmarEmailReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateTyCWhatsapp", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateTyCWhatsappRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlFirmado;
        
        public updateTyCWhatsappRequest() {
        }
        
        public updateTyCWhatsappRequest(string xmlFirmado) {
            this.xmlFirmado = xmlFirmado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateTyCWhatsappResponse", WrapperNamespace="http://services.mya.ar.bsch", IsWrapped=true)]
    public partial class updateTyCWhatsappResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string updateTyCWhatsappReturn;
        
        public updateTyCWhatsappResponse() {
        }
        
        public updateTyCWhatsappResponse(string updateTyCWhatsappReturn) {
            this.updateTyCWhatsappReturn = updateTyCWhatsappReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesChannel : Isban.MapsMB.Business.MYAService.Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<Isban.MapsMB.Business.MYAService.Services>, Isban.MapsMB.Business.MYAService.Services {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.getEstadoClienteResponse Isban.MapsMB.Business.MYAService.Services.getEstadoCliente(Isban.MapsMB.Business.MYAService.getEstadoClienteRequest request) {
            return base.Channel.getEstadoCliente(request);
        }
        
        public string getEstadoCliente(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.getEstadoClienteRequest inValue = new Isban.MapsMB.Business.MYAService.getEstadoClienteRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.getEstadoClienteResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).getEstadoCliente(inValue);
            return retVal.getEstadoClienteReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getEstadoClienteResponse> Isban.MapsMB.Business.MYAService.Services.getEstadoClienteAsync(Isban.MapsMB.Business.MYAService.getEstadoClienteRequest request) {
            return base.Channel.getEstadoClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getEstadoClienteResponse> getEstadoClienteAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.getEstadoClienteRequest inValue = new Isban.MapsMB.Business.MYAService.getEstadoClienteRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).getEstadoClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.getStatusClienteResponse Isban.MapsMB.Business.MYAService.Services.getStatusCliente(Isban.MapsMB.Business.MYAService.getStatusClienteRequest request) {
            return base.Channel.getStatusCliente(request);
        }
        
        public string getStatusCliente(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.getStatusClienteRequest inValue = new Isban.MapsMB.Business.MYAService.getStatusClienteRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.getStatusClienteResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).getStatusCliente(inValue);
            return retVal.getStatusClienteReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getStatusClienteResponse> Isban.MapsMB.Business.MYAService.Services.getStatusClienteAsync(Isban.MapsMB.Business.MYAService.getStatusClienteRequest request) {
            return base.Channel.getStatusClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getStatusClienteResponse> getStatusClienteAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.getStatusClienteRequest inValue = new Isban.MapsMB.Business.MYAService.getStatusClienteRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).getStatusClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.getEstadoClienteV3Response Isban.MapsMB.Business.MYAService.Services.getEstadoClienteV3(Isban.MapsMB.Business.MYAService.getEstadoClienteV3Request request) {
            return base.Channel.getEstadoClienteV3(request);
        }
        
        public string getEstadoClienteV3(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.getEstadoClienteV3Request inValue = new Isban.MapsMB.Business.MYAService.getEstadoClienteV3Request();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.getEstadoClienteV3Response retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).getEstadoClienteV3(inValue);
            return retVal.getEstadoClienteV3Return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getEstadoClienteV3Response> Isban.MapsMB.Business.MYAService.Services.getEstadoClienteV3Async(Isban.MapsMB.Business.MYAService.getEstadoClienteV3Request request) {
            return base.Channel.getEstadoClienteV3Async(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getEstadoClienteV3Response> getEstadoClienteV3Async(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.getEstadoClienteV3Request inValue = new Isban.MapsMB.Business.MYAService.getEstadoClienteV3Request();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).getEstadoClienteV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.updateMensajeResponse Isban.MapsMB.Business.MYAService.Services.updateMensaje(Isban.MapsMB.Business.MYAService.updateMensajeRequest request) {
            return base.Channel.updateMensaje(request);
        }
        
        public string updateMensaje(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.updateMensajeRequest inValue = new Isban.MapsMB.Business.MYAService.updateMensajeRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.updateMensajeResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).updateMensaje(inValue);
            return retVal.updateMensajeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateMensajeResponse> Isban.MapsMB.Business.MYAService.Services.updateMensajeAsync(Isban.MapsMB.Business.MYAService.updateMensajeRequest request) {
            return base.Channel.updateMensajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateMensajeResponse> updateMensajeAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.updateMensajeRequest inValue = new Isban.MapsMB.Business.MYAService.updateMensajeRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).updateMensajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.updateMensajeRecargaResponse Isban.MapsMB.Business.MYAService.Services.updateMensajeRecarga(Isban.MapsMB.Business.MYAService.updateMensajeRecargaRequest request) {
            return base.Channel.updateMensajeRecarga(request);
        }
        
        public string updateMensajeRecarga(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.updateMensajeRecargaRequest inValue = new Isban.MapsMB.Business.MYAService.updateMensajeRecargaRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.updateMensajeRecargaResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).updateMensajeRecarga(inValue);
            return retVal.updateMensajeRecargaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateMensajeRecargaResponse> Isban.MapsMB.Business.MYAService.Services.updateMensajeRecargaAsync(Isban.MapsMB.Business.MYAService.updateMensajeRecargaRequest request) {
            return base.Channel.updateMensajeRecargaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateMensajeRecargaResponse> updateMensajeRecargaAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.updateMensajeRecargaRequest inValue = new Isban.MapsMB.Business.MYAService.updateMensajeRecargaRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).updateMensajeRecargaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.updateDestinosResponse Isban.MapsMB.Business.MYAService.Services.updateDestinos(Isban.MapsMB.Business.MYAService.updateDestinosRequest request) {
            return base.Channel.updateDestinos(request);
        }
        
        public string updateDestinos(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.updateDestinosRequest inValue = new Isban.MapsMB.Business.MYAService.updateDestinosRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.updateDestinosResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).updateDestinos(inValue);
            return retVal.updateDestinosReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateDestinosResponse> Isban.MapsMB.Business.MYAService.Services.updateDestinosAsync(Isban.MapsMB.Business.MYAService.updateDestinosRequest request) {
            return base.Channel.updateDestinosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateDestinosResponse> updateDestinosAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.updateDestinosRequest inValue = new Isban.MapsMB.Business.MYAService.updateDestinosRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).updateDestinosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.registrarConDestinoResponse Isban.MapsMB.Business.MYAService.Services.registrarConDestino(Isban.MapsMB.Business.MYAService.registrarConDestinoRequest request) {
            return base.Channel.registrarConDestino(request);
        }
        
        public string registrarConDestino(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.registrarConDestinoRequest inValue = new Isban.MapsMB.Business.MYAService.registrarConDestinoRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.registrarConDestinoResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).registrarConDestino(inValue);
            return retVal.registrarConDestinoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.registrarConDestinoResponse> Isban.MapsMB.Business.MYAService.Services.registrarConDestinoAsync(Isban.MapsMB.Business.MYAService.registrarConDestinoRequest request) {
            return base.Channel.registrarConDestinoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.registrarConDestinoResponse> registrarConDestinoAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.registrarConDestinoRequest inValue = new Isban.MapsMB.Business.MYAService.registrarConDestinoRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).registrarConDestinoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.getParametrosResponse Isban.MapsMB.Business.MYAService.Services.getParametros(Isban.MapsMB.Business.MYAService.getParametrosRequest request) {
            return base.Channel.getParametros(request);
        }
        
        public string getParametros(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.getParametrosRequest inValue = new Isban.MapsMB.Business.MYAService.getParametrosRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.getParametrosResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).getParametros(inValue);
            return retVal.getParametrosReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getParametrosResponse> Isban.MapsMB.Business.MYAService.Services.getParametrosAsync(Isban.MapsMB.Business.MYAService.getParametrosRequest request) {
            return base.Channel.getParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getParametrosResponse> getParametrosAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.getParametrosRequest inValue = new Isban.MapsMB.Business.MYAService.getParametrosRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).getParametrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.registrarResponse Isban.MapsMB.Business.MYAService.Services.registrar(Isban.MapsMB.Business.MYAService.registrarRequest request) {
            return base.Channel.registrar(request);
        }
        
        public string registrar(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.registrarRequest inValue = new Isban.MapsMB.Business.MYAService.registrarRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.registrarResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).registrar(inValue);
            return retVal.registrarReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.registrarResponse> Isban.MapsMB.Business.MYAService.Services.registrarAsync(Isban.MapsMB.Business.MYAService.registrarRequest request) {
            return base.Channel.registrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.registrarResponse> registrarAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.registrarRequest inValue = new Isban.MapsMB.Business.MYAService.registrarRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).registrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.updateEstadoClienteResponse Isban.MapsMB.Business.MYAService.Services.updateEstadoCliente(Isban.MapsMB.Business.MYAService.updateEstadoClienteRequest request) {
            return base.Channel.updateEstadoCliente(request);
        }
        
        public string updateEstadoCliente(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.updateEstadoClienteRequest inValue = new Isban.MapsMB.Business.MYAService.updateEstadoClienteRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.updateEstadoClienteResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).updateEstadoCliente(inValue);
            return retVal.updateEstadoClienteReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateEstadoClienteResponse> Isban.MapsMB.Business.MYAService.Services.updateEstadoClienteAsync(Isban.MapsMB.Business.MYAService.updateEstadoClienteRequest request) {
            return base.Channel.updateEstadoClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateEstadoClienteResponse> updateEstadoClienteAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.updateEstadoClienteRequest inValue = new Isban.MapsMB.Business.MYAService.updateEstadoClienteRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).updateEstadoClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.getSuscripcionesResponse Isban.MapsMB.Business.MYAService.Services.getSuscripciones(Isban.MapsMB.Business.MYAService.getSuscripcionesRequest request) {
            return base.Channel.getSuscripciones(request);
        }
        
        public string getSuscripciones(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.getSuscripcionesRequest inValue = new Isban.MapsMB.Business.MYAService.getSuscripcionesRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.getSuscripcionesResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).getSuscripciones(inValue);
            return retVal.getSuscripcionesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getSuscripcionesResponse> Isban.MapsMB.Business.MYAService.Services.getSuscripcionesAsync(Isban.MapsMB.Business.MYAService.getSuscripcionesRequest request) {
            return base.Channel.getSuscripcionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.getSuscripcionesResponse> getSuscripcionesAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.getSuscripcionesRequest inValue = new Isban.MapsMB.Business.MYAService.getSuscripcionesRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).getSuscripcionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.confirmarEmailResponse Isban.MapsMB.Business.MYAService.Services.confirmarEmail(Isban.MapsMB.Business.MYAService.confirmarEmailRequest request) {
            return base.Channel.confirmarEmail(request);
        }
        
        public string confirmarEmail(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.confirmarEmailRequest inValue = new Isban.MapsMB.Business.MYAService.confirmarEmailRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.confirmarEmailResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).confirmarEmail(inValue);
            return retVal.confirmarEmailReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.confirmarEmailResponse> Isban.MapsMB.Business.MYAService.Services.confirmarEmailAsync(Isban.MapsMB.Business.MYAService.confirmarEmailRequest request) {
            return base.Channel.confirmarEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.confirmarEmailResponse> confirmarEmailAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.confirmarEmailRequest inValue = new Isban.MapsMB.Business.MYAService.confirmarEmailRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).confirmarEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Isban.MapsMB.Business.MYAService.updateTyCWhatsappResponse Isban.MapsMB.Business.MYAService.Services.updateTyCWhatsapp(Isban.MapsMB.Business.MYAService.updateTyCWhatsappRequest request) {
            return base.Channel.updateTyCWhatsapp(request);
        }
        
        public string updateTyCWhatsapp(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.updateTyCWhatsappRequest inValue = new Isban.MapsMB.Business.MYAService.updateTyCWhatsappRequest();
            inValue.xmlFirmado = xmlFirmado;
            Isban.MapsMB.Business.MYAService.updateTyCWhatsappResponse retVal = ((Isban.MapsMB.Business.MYAService.Services)(this)).updateTyCWhatsapp(inValue);
            return retVal.updateTyCWhatsappReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateTyCWhatsappResponse> Isban.MapsMB.Business.MYAService.Services.updateTyCWhatsappAsync(Isban.MapsMB.Business.MYAService.updateTyCWhatsappRequest request) {
            return base.Channel.updateTyCWhatsappAsync(request);
        }
        
        public System.Threading.Tasks.Task<Isban.MapsMB.Business.MYAService.updateTyCWhatsappResponse> updateTyCWhatsappAsync(string xmlFirmado) {
            Isban.MapsMB.Business.MYAService.updateTyCWhatsappRequest inValue = new Isban.MapsMB.Business.MYAService.updateTyCWhatsappRequest();
            inValue.xmlFirmado = xmlFirmado;
            return ((Isban.MapsMB.Business.MYAService.Services)(this)).updateTyCWhatsappAsync(inValue);
        }
    }
}
